version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: travako_mysql_db_0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=arkitik_travako
      - MYSQL_PASSWORD=arkitik_travako
      - MYSQL_DATABASE=arkitik_travako
      - MYSQL_ROOT_PASSWORD=arkitik_travako
  travako_redis:
    image: redis:latest
    networks:
      - development-net
    ports:
      - "6371:6379"
    volumes:
      - redis_data:/data
    restart: always
volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: ~/.recon/redis/data-tmp
      o: bind
networks:
  development-net:
    driver: local