server:
  port: 8093
spring:
  datasource:
    url: jdbc:mysql://192.168.148.2:3306/arkitik_travako
    username: arkitik_travako
    password: arkitik_travako
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
arkitik:
  travako:
    config:
      server-key: travako
      runner:
        key: travako-runner-1
        duplication-detection: true
        jobs-event: 10s
      misfiring:
        enabled: true
        run-interval-minutes: 1
        threshold-seconds: 120
    database:
      exposed:
        datasource:
          url: jdbc:postgresql://localhost:5432/arkitik_travako
          username: saturn_pps_central
          password: saturn_pps_central
          driver-class-name: org.postgresql.Driver
logging:
  level:
    io:
      arkitik: trace
    Exposed: off
